version: '3'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bug_tracker
    ports:
      - "32700:5432"

  web:
    build: .
    command: bash -c "alembic upgrade head && python main.py"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

