"""initial

Revision ID: ae2cd3de84ff
Revises: 
Create Date: 2022-02-18 16:03:50.718300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2cd3de84ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=True),
    sa.Column('hash_password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('header', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('executor', sa.BigInteger(), nullable=True),
    sa.Column('creator', sa.BigInteger(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('parent_task', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], name='fk_tasks_users_id_creator'),
    sa.ForeignKeyConstraint(['executor'], ['users.id'], name='fk_tasks_users_id_executor'),
    sa.ForeignKeyConstraint(['parent_task'], ['tasks.id'], name='fk_tasks_tasks_id_parent_task'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('taskblocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('from_task', sa.BigInteger(), nullable=True),
    sa.Column('to_task', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['from_task'], ['tasks.id'], name='fk_taskblocks_tasks_from_task_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_task'], ['tasks.id'], name='fk_taskblocks_tasks_to_task_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskblocks_id'), 'taskblocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskblocks_id'), table_name='taskblocks')
    op.drop_table('taskblocks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
